version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5332:5432"
    environment:
      POSTGRES_USER: mustapha
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  postgres-data: